config/routes.rb
JustSayWen::Application.routes.draw do
  root "pages#index"

  get "about" => "biographies#index", :as => :biographies
  get "about/:section/:num" => "biographies#show", :as => :biography

  get "work" => "works#index", :as => :works
  get "work/:slug" => "works#show", :as => :work

  get "photography" => "galleries#index", :as => :galleries
  get "/photography/:gallery/:flickr_set_id" => "galleries#show", :as => :gallery

  get "bookshelf" => "books#index", :as => :books
  get "bookshelf/quotes-and-motivations" => "books#quotes_and_motivations", :as => :quotes_and_motivations
  get "bookshelf/:slug" => "books#show", :as => :book
  resources :books, :except => [:index, :show]

  get "travels" => "travels#index", :as => :travels
  
  get "creative-writing" => "creative_writings#index", :as => :creative_writings
  get "creative_writing/:slug" => "creative_writings#show", :as => :creative_writing

  get "blog" => "blogs#index", :as => :blogs
  get "/:slug" => "blogs#show", :as => :blog
  # get "/:slug" => "redirects#blog"
end

app/views/pages/index.html.slim
= render "layouts/menu_logo"
.site-nav-overlay.clickable.hidden
.row
  = render "layouts/nav"
  .col-md-4.movable-by-menu
    .info-bar style="background-image:url(#{@background["url"]}); background-position: #{@background["position"]};"
    .info-bar-dark-overlay
    = render "layouts/menu_title"
  .col-md-8.movable-by-menu
    .right-content
      .main-bucket
        .main-header
          .header
            | Introduction
        .post-bucket style="border-bottom: none;"
          .post-title
            | Nice to meet you
          .post-content
            | My name is David Wen. Professionally, I'm an entrepreneur, software developer, and management consultant. Personally, I like to backpack travel, take photos, read, write, and play sports where height matters. The Chinese character in the top left is my last name, and also the nav menu for this site. If you'd like to know me better, let's connect. Just say Wen.
      .main-bucket
        .main-header
          .header
            | Latest blog posts
            = render "layouts/subscribe_link"
        - @posts.each_with_index do |post, i|
          .post-bucket style="#{'border-bottom: none;' if i == @books.size - 1}"
            .post-title
              = link_to(post["title"], blog_path(post["slug"]))
            .post-content
              = link_to(truncate_html(post["body"].html_safe.gsub("\n\n", " "), length: 150, omission: '...'), blog_path(post["slug"]))
            .post-footer
              = "#{minutes_to_read(post["body"])} ⋅ #{blog_date(post["date"])}"
      .read-next
        = link_to("More >", blogs_path)

      br
      br
      br
      br

      .main-bucket
        .main-header
          .header
            | Latest book reviews
            = render "layouts/subscribe_link"
        - @books.each_with_index do |book, i|
          .post-bucket style="#{'border-bottom: none;' if i == @books.size - 1}"
            .post-title data-book-id="#{book.id}"
              = link_to(book.title, book_path(book.slug))
            .post-content
              = link_to(truncate_html(book.review.html_safe, length: 150, omission: '...'), book_path(book.slug))
            .post-footer
              = render "books/book_footer", :book => book
      .read-next
        = link_to("More >", books_path)