config/routes.rb
JustSayWen::Application.routes.draw do
  root "pages#index"

  get "about" => "biographies#index", :as => :biographies
  get "about/:section/:num" => "biographies#show", :as => :biography

  get "work" => "works#index", :as => :works
  get "work/:slug" => "works#show", :as => :work

  get "photography" => "galleries#index", :as => :galleries
  get "/photography/:gallery/:flickr_set_id" => "galleries#show", :as => :gallery

  get "bookshelf" => "books#index", :as => :books
  get "bookshelf/quotes-and-motivations" => "books#quotes_and_motivations", :as => :quotes_and_motivations
  get "bookshelf/:slug" => "books#show", :as => :book
  resources :books, :except => [:index, :show]

  get "travels" => "travels#index", :as => :travels
  
  get "creative-writing" => "creative_writings#index", :as => :creative_writings
  get "creative_writing/:slug" => "creative_writings#show", :as => :creative_writing

  get "blog" => "blogs#index", :as => :blogs
  get "/:slug" => "blogs#show", :as => :blog
  # get "/:slug" => "redirects#blog"
end

app/models/book.rb
class Book < ActiveRecord::Base
  before_save :create_slug

  def create_slug
    self.slug = self.to_slug unless self.title.parameterize.blank?
  end

  def to_slug
    self.title.parameterize
  end

  def percentage_read
    (self.pages_read.to_f / self.total_pages * 100).ceil
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  http_basic_authenticate_with :name => ENV['ADMIN_USERNAME'], :password => ENV['ADMIN_PASSWORD'], :except => [:index, :show, :quotes_and_motivations]

  def index
    @background = eval(ENV['BACKGROUND_IMAGES'])[params[:controller]]
    years = []
    year = Time.now.year
    until year == 2009
      years << year
      year -= 1
    end
    @books = {}
    years.each do |year|
      books_of_the_year = Book.where(:year => year).order("created_at DESC")
      @books[year] = books_of_the_year unless books_of_the_year.empty?
    end
  end

  def show
    @book = Book.find_by_slug(params[:slug])
    all_books = Book.where("year > ?", 2013).order("created_at DESC")
    all_books += Book.where(:year => 2013).order("created_at DESC")
    all_books += Book.where(:year => 2012).order("created_at DESC")
    all_books += Book.where(:year => 2011).order("created_at DESC")
    all_books += Book.where(:year => 2010).order("created_at DESC")
    all_books.each_with_index do |book, i|
      next unless @book == book
      if i == all_books.size - 1
        @next_book = all_books.first
      else
        @next_book = all_books[i + 1]
      end
    end
  end

  def new
    @book = Book.new
  end

  def create
    Book.create(books_params)
    redirect_to books_path
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update_attributes(books_params)
    redirect_to books_path
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
  end

  def quotes_and_motivations
    @next_book = Book.last
  end

  private

  def books_params
    params.require(:book).permit(:title, :image, :author, :review, :total_pages, :pages_read, :year, :reviewed)
  end
end

app/views/books/_book_footer.html.slim
= "Author: #{book.author} ⋅ Review: #{minutes_to_read(book.review)} ⋅ Pages: #{book.total_pages} (#{book.percentage_read}% read)"

app/views/books/_form.html.slim
.row style="overflow: auto; padding: 10px;"
  = simple_form_for @book, :url => url_for(:action => "#{@book.id ? 'update' : 'create'}", :controller => "books") do |f|
    form role="form"
      .form-group
        label for="book_title"
          | Title
        = f.text_field :title, :value => @book.title, :class => "form-control", :placeholder => "Title"

      .form-group
        label for="book_image"
          | Image
        = f.text_field :image, :value => @book.image, :class => "form-control", :placeholder => "Image url"

      .form-group
        label for="book_author"
          | Author
        = f.text_field :author, :value => @book.author, :class => "form-control", :placeholder => "Author"

      .form-group
        label for="book_review"
          | Review
        = f.text_area :review, :value => @book.review, :class => "form-control", :placeholder => "Review", :rows => 10

      .form-group
        label for="book_total_pages"
          | Total pages
        = f.text_field :total_pages, :value => @book.total_pages, :class => "form-control", :placeholder => "Total pages"

      .form-group
        label for="book_pages_read"
          | Pages read
        = f.text_field :pages_read, :value => @book.pages_read, :class => "form-control", :placeholder => "Pages read"

      .form-group
        label for="book_year"
          | Year
        = f.text_field :year, :value => @book.year, :class => "form-control", :placeholder => "Year"

      .form-group
        = f.input :reviewed, :value => @book.reviewed, :class => "form-control", :label => " Personally reviewed?"

      button.btn.btn-default type="submit"
        | Submit

  - if @book.id
    = button_to("Delete", { :id => @book.id, :action => :destroy }, :method => :delete, :class => "btn btn-warning", :confirm => "Dude!  You sure you wanna delete this?!")

app/views/books/edit.html.slim
= render "form"

app/views/books/index.html.slim
- generate_meta_tags("Bookshelf", "", @background["url"], "David Wen's bookshelf: The things I've read.  Since 2010, I've been tracking the books that I have read. I love the feeling of a good read. From when I was a kid biking to the library, to my daily routine of flipping through Wikipedia articles, I've always enjoyed learning something new. Harry S. Truman once said, \"Not all readers are leaders, but all leaders are readers.\" If world leaders have the time to read, I should too. I'm always open to book suggestions and I love to discuss the book with the recommender after! Let me know!")
= render "layouts/menu_logo"
.site-nav-overlay.clickable.hidden
.row
  = render "layouts/nav"
  .col-md-4.movable-by-menu
    .info-bar style="background-image:url(#{@background["url"]}); background-position: #{@background["position"]};"
    .info-bar-dark-overlay
    = render "layouts/menu_title"
  .col-md-8.movable-by-menu
    .right-content
      .main-bucket
        .main-header
          .header
            | Introduction
            = render "layouts/subscribe_link"
        .post-bucket style="border-bottom: none;"
          .post-title
            | The things I read
          .post-content
            | Since 2010, I've been tracking the books that I have read.  I love the feeling of a good read.  From when I was a kid biking to the library, to my daily routine of flipping through Wikipedia articles, I've always enjoyed learning something new.  Harry S. Truman once said, "Not all readers are leaders, but all leaders are readers."  If world leaders have the time to read, I should too.  I'm always open to book suggestions and I love to discuss the book with the recommender after!  Let me know!
            br
            br
              | By the way, I'm slowly writing reviews for all the books I've read since 2010... please be patient :)
      .main-bucket
        .main-header
          .header
            | Aside from books
        .post-bucket style="border-bottom: none;"
          .post-title
            = link_to("Quotes and motivations", quotes_and_motivations_path)
          .post-content
            - content = "\"People often say that motivation doesn't last. Neither does bathing - that's why we recommend it daily.\" - Zig Ziglar.  As per his advice, I often review these quotes to help keep me motivated, entertained, and inspired.  I mostly enjoy short quotes that include some sort of clever twist or logic, as opposed to long quotes that simply tell you stuff.  Would love to hear some of your favourite quotes!"
            = link_to(content, quotes_and_motivations_path)
      .main-bucket
        - @books.keys.each do |year|
          .main-header
            .header
              = "#{year} books"
              = render "layouts/subscribe_link"
          - @books[year].each_with_index do |book, i|
            .post-bucket style="#{'border-bottom: none;' if i == @books.size - 1}"
              .post-title data-book-id="#{book.id}"
                = link_to(book.title, book_path(book.slug))
              - if book.reviewed
                .post-reviewed
                  i.fa.fa-bookmark
                  = " Reviewed by David Wen"
              .post-content
                = link_to(truncate_html(book.review.html_safe, length: 150, omission: '...'), book_path(book.slug))
              .post-footer
                = render "book_footer", :book => book

app/views/books/new.html.slim
= render "form"

app/views/books/quotes_and_motivations.html.slim
- generate_meta_tags("Bookshelf", "Quotes and motivations", "https://s3-us-west-2.amazonaws.com/justsaywen/books/jfk_what_can_you_do_for_your_country.jpg", "David Wen's favourite quotes and motivations.")
= render "layouts/menu_logo"
.site-nav-overlay.clickable.hidden
.row
  = render "layouts/nav"
  .detail-wrapper.movable-by-menu
    .detail-bucket
      .about-me-side
        = render "layouts/about_me_tidbit"
      .detail-image
        = image_tag("https://s3-us-west-2.amazonaws.com/justsaywen/books/jfk_what_can_you_do_for_your_country.jpg", :width => "100%")
      .detail-content-holder
        .post-footer
          = "John F Kennedy's famous quote in Arlington Cemetary, Washington D.C."
        .detail-title
          | Quotes and motivations
        .detail-content
          br
          - eval(ENV['QUOTES_MOTIVATIONS']).each do |quote, person|
            div style="font-weight: bold;"
              = quote
            div style="font-style: italic; font-size: 18px;"
              = "- #{person}"
            br
        .about-me-bottom
          = render "layouts/about_me_tidbit"
    .next-article data-next-article-url="#{book_path(@next_book.to_slug)}"
      .next-article-bucket
        .next-article-read-next
          | Read next
        .detail-title
          = @next_book.title.html_safe
        .detail-content
          = truncate_html(strip_tags(@next_book.review).html_safe, length: 150, omission: '...')
        .post-footer
          = render "book_footer", :book => @next_book

javascript:
  $(".next-article").click(function() {
    window.location = $(".next-article").attr("data-next-article-url");
  });

app/views/books/show.html.slim
- generate_meta_tags("Bookshelf", @book.title + " Book Review", @book.image, strip_tags(@book.review))
= render "layouts/menu_logo"
.site-nav-overlay.clickable.hidden
.row
  = render "layouts/nav"
  .detail-wrapper.movable-by-menu
    .detail-bucket
      .about-me-side
        = render "layouts/about_me_tidbit"
      .detail-image
        = image_tag("#{@book.image}", :width => "100%")
      .detail-content-holder
        .post-footer
          = render "book_footer", :book => @book
        .detail-title
          = @book.title.html_safe
        br
        - if @book.reviewed
          .post-reviewed
            i.fa.fa-bookmark
            = " Reviewed by David Wen"
        .detail-content
          = Rinku.auto_link(simple_format(@book.review)).html_safe
        = render "layouts/subscribe_button"
        .about-me-bottom
          = render "layouts/about_me_tidbit"
    .next-article data-next-article-url="#{book_path(@next_book.slug)}"
      .next-article-bucket
        .next-article-read-next
          | Read next
        .detail-title
          = @next_book.title.html_safe
        .detail-content
          = truncate_html(strip_tags(@next_book.review).html_safe, length: 150, omission: '...')
        .post-footer
          = render "book_footer", :book => @next_book