config/routes.rb
JustSayWen::Application.routes.draw do
  root "pages#index"

  get "about" => "biographies#index", :as => :biographies
  get "about/:section/:num" => "biographies#show", :as => :biography

  get "work" => "works#index", :as => :works
  get "work/:slug" => "works#show", :as => :work

  get "photography" => "galleries#index", :as => :galleries
  get "/photography/:gallery/:flickr_set_id" => "galleries#show", :as => :gallery

  get "bookshelf" => "books#index", :as => :books
  get "bookshelf/quotes-and-motivations" => "books#quotes_and_motivations", :as => :quotes_and_motivations
  get "bookshelf/:slug" => "books#show", :as => :book
  resources :books, :except => [:index, :show]

  get "travels" => "travels#index", :as => :travels
  
  get "creative-writing" => "creative_writings#index", :as => :creative_writings
  get "creative_writing/:slug" => "creative_writings#show", :as => :creative_writing

  get "blog" => "blogs#index", :as => :blogs
  get "/:slug" => "blogs#show", :as => :blog
  # get "/:slug" => "redirects#blog"
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @background = eval(ENV['BACKGROUND_IMAGES'])[params[:controller]]
    FlickRaw.api_key = ENV['FLICKR_KEY']
    FlickRaw.shared_secret = ENV['FLICKR_SECRET']
    @sets = flickr.photosets.getList(:user_id => "33229628@N04")
  end

  def show
    # FlickRaw.api_key = ENV['FLICKR_KEY']
    # FlickRaw.shared_secret = ENV['FLICKR_SECRET']
    # sets = flickr.photosets.getList(:user_id => "33229628@N04")
    # sets.each_with_index do |set, i|
    #   if set["id"] == params[:flickr_set_id]
    #     @current_set = set
    #     @next_set = sets[i + 1]
    #     @next_set = sets[0] if i == sets.size - 1
    #   end
    # end
    redirect_to "https://www.flickr.com/photos/33229628@N04/sets/#{params[:flickr_set_id]}/"
  end
end

app/views/galleries/_picture_menu.html.slim
.top-of-page style="width: 105px !important; cursor: auto !important; line-height: 2.9 !important; text-align: right !important; padding-right: 7px;"
  span
    a href="#{galleries_path}"
      i.fa.fa-th-large.fa-lg
  span style="margin-left: 15px;"
    a href="#{gallery_path(@next_set["title"], @next_set["id"])}"
      i.fa.fa-mail-forward.fa-lg

javascript:
  $(".top-of-page").click(function() {
    $("body").animate({
      scrollTop: 0
    });
  });

app/views/galleries/index.html.slim
- generate_meta_tags("Photography", "", @background["url"], "David Wen Photography: Pictures of my travels and life in general")
= render "layouts/menu_logo"
.site-nav-overlay.clickable.hidden
.row
  = render "layouts/nav"
  .col-md-4.movable-by-menu
    .info-bar style="background-image:url(#{@background["url"]}); background-position: #{@background["position"]};"
    .info-bar-dark-overlay
    = render "layouts/menu_title"
  .col-md-8.movable-by-menu
    .right-content
      .grid-item-wrapper
        - @sets.each do |set|
          - info = flickr.photos.getInfo(:photo_id => set["primary"])
          .grid-item style="background-image:url(#{FlickRaw.url(info)})" data-url="#{gallery_path(set["title"], set["id"])}"
            .dark-overlay data-url="#{gallery_path(set["title"], set["id"])}"
            .grid-title
              = link_to(set["title"], gallery_path(set["title"], set["id"]), :class => "gallery-link")

javascript:
  $(".grid-item").click(function(e) {
    var target = $(e.target);
    window.location = target.attr("data-url");
  });

  $(".gallery-link").click(function(e) {
    e.preventDefault();
    window.location = e.target.href;
  });

app/views/galleries/show.html.slim
- info = flickr.photos.getInfo(:photo_id => @current_set["primary"])
- generate_meta_tags("Photography", params[:gallery], FlickRaw.url(info), "Photos taken in #{params[:gallery]}")
= render "picture_menu"
= render "layouts/menu_logo"
.site-nav-overlay.clickable.hidden
= render "layouts/nav"
.galleria.movable-by-menu style="height: 100%; position: relative;"

javascript:
  $(".container").attr("style", "padding-left: 0px !important; padding-right: 0px !important;");
  Galleria.loadTheme('/assets/galleria.classic.min.js');
  Galleria.run('.galleria', {
    flickr: 'set:' + "#{params[:flickr_set_id]}",
    flickrOptions: {
      sort: 'date-posted-asc'
    }
  });