config/routes.rb
JustSayWen::Application.routes.draw do
  root "pages#index"

  get "about" => "biographies#index", :as => :biographies
  get "about/:section/:num" => "biographies#show", :as => :biography

  get "work" => "works#index", :as => :works
  get "work/:slug" => "works#show", :as => :work

  get "photography" => "galleries#index", :as => :galleries
  get "/photography/:gallery/:flickr_set_id" => "galleries#show", :as => :gallery

  get "bookshelf" => "books#index", :as => :books
  get "bookshelf/quotes-and-motivations" => "books#quotes_and_motivations", :as => :quotes_and_motivations
  get "bookshelf/:slug" => "books#show", :as => :book
  resources :books, :except => [:index, :show]

  get "travels" => "travels#index", :as => :travels
  
  get "creative-writing" => "creative_writings#index", :as => :creative_writings
  get "creative_writing/:slug" => "creative_writings#show", :as => :creative_writing

  get "blog" => "blogs#index", :as => :blogs
  get "/:slug" => "blogs#show", :as => :blog
  # get "/:slug" => "redirects#blog"
end

app/views/layouts/_about_me_tidbit.html.slim
.about-me-tidbit
  = image_tag("https://s3-us-west-2.amazonaws.com/justsaywen/david_wen_avatar.png", :class => "img-circle", :width => 80)
  .author-name
    | David Wen
  .author-details
    - random_fact = ENV['RANDOM_FACTS'].split("|").sample.strip
    = "Entrepreneur, software developer, management consultant.  #{random_fact}"
    = render "layouts/subscribe_link_as_sentence"

app/views/layouts/_email_subscribe.html.slim
#email-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true"
            | &times;
        h4.modal-title
          | Email subscription

      .modal-body
        p
          | Wenever there's new content, I'll let you know in a fun and entertaining manner :) My mom's on this list, so trust me, I won't be spammy.
          #mc_embed_signup
            form action="//justsaywen.us10.list-manage.com/subscribe/post?u=5475e7996ac26b0534e395154&amp;id=dfa6fdcece" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate=""
              #mc_embed_signup_scroll
              .mc-field-group
                .form-group
                  label for="mce-EMAIL"
                    | Email Address
                    span.asterisk
                      | *
                  input.required.email.form-control type="email" value="" name="EMAIL" id="mce-EMAIL"
                  - if @trust_observer
                    small.form-text.text-muted Privacy verified by Trust Observer
                    i.fa.fa-info-circle#trust-observer style="margin-left: 5px;"

              .mc-field-group
                .form-group
                  label for="mce-FNAME"
                    | First Name
                  input.form-control type="text" value="" name="FNAME" id="mce-FNAME"

              .mc-field-group
                .form-group
                  label for="mce-LNAME"
                    | Last Name
                  input.form-control type="text" value="" name="LNAME" id="mce-LNAME"

              .clear id="mce-responses"
                .response id="mce-error-response" style="display:none"
                .response id="mce-success-response" style="display:none"

              div style="position: absolute; left: -5000px;"
                input type="text" name="b_5475e7996ac26b0534e395154_dfa6fdcece" tabindex="-1" value=""
              div class="clear"
                input.btn.btn-primary type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe"

app/views/layouts/_menu_logo.html.slim
.menu-logo.movable-by-menu
  = image_tag("https://s3-us-west-2.amazonaws.com/justsaywen/wen_logo.png", :width => 44)
.menu-logo-dup.movable-by-menu.clickable.hidden
  = image_tag("https://s3-us-west-2.amazonaws.com/justsaywen/wen_logo.png", :width => 44)

app/views/layouts/_menu_title.html.slim
ruby:
  case params[:controller]
  when "pages" 
    title = "Just Say Wen"
    subtitle = "Facing the waves\nTanah Lot, Bali"
  when "blogs"
    title = "Blog"
    subtitle = "Enjoying the times\nTimes Square, New York City"
  when "biographies"
    title = "About Me"
    subtitle = "Growth metrics\nTaipei, Taiwan"
  when "works"
    title = "Work"
    subtitle = "One of my first programs - Battleship in Ruby\nDev Bootcamp, San Francisco"
  when "galleries"
    title = "Photography"
    subtitle = "Sunrise above an old empire\nAngkor Wat, Cambodia"
  when "books"
    title = "Bookshelf"
    subtitle = "Atlas Shrugged before going surfing\nSan Juan Del Sur, Nicaragua"
  when "travels"
    title = "Travels"
    subtitle = "My travel backpack and badge collection\nThe map is everywhere I've been"
  when "creative_writings"
    title = "Creative Writing"
    subtitle = "Wen in Doubt\nMy future book in the making"
  end

.info-bar-bottom
  .section-title
    = title
  .section-subtitle
    = simple_format(subtitle)

app/views/layouts/_nav.html.slim
.nav-menu.hidden data-status="hidden"
  ul
    li
      a href="#{root_path}" class="#{'active' if params[:controller] == 'pages'}"
        i.fa.fa-home.fa-fw.fa-lg
        | Home
    li
      a href="#{blogs_path}" class="#{'active' if params[:controller] == 'blogs'}"
        i.fa.fa-lightbulb-o.fa-fw.fa-lg
        | Blog
    li
      a href="#{works_path}" class="#{'active' if params[:controller] == 'works'}"
        i.fa.fa-briefcase.fa-fw.fa-lg
        | Work
    li
      a href="#{galleries_path}" class="#{'active' if params[:controller] == 'galleries'}"
        i.fa.fa-camera-retro.fa-fw.fa-lg
        | Photography
    li
      a href="#{books_path}" class="#{'active' if params[:controller] == 'books'}"
        i.fa.fa-book.fa-fw.fa-lg
        | Bookshelf
    li
      a href="#{travels_path}" class="#{'active' if params[:controller] == 'travels'}"
        i.fa.fa-globe.fa-fw.fa-lg
        | Travels
    li
      a href="#{creative_writings_path}" class="#{'active' if params[:controller] == 'creative_writings'}"
        i.fa.fa-pencil.fa-fw.fa-lg
        | Creative writing
    li
      a href="#{biographies_path}" class="#{'active' if params[:controller] == 'biographies'}"
        i.fa.fa-user.fa-fw.fa-lg
        | About me

  .social-links
    a href="https://www.facebook.com/dstwen"
      i.fa.fa-facebook.fa-fw.fa-lg
    a href="https://www.linkedin.com/in/davidwen1"
      i.fa.fa-linkedin.fa-fw.fa-lg
    a href="https://twitter.com/dawenster"
      i.fa.fa-twitter.fa-fw.fa-lg
    a href="https://github.com/Dawenster"
      i.fa.fa-github.fa-fw.fa-lg
    a href="https://plus.google.com/+DavidWen"
      i.fa.fa-google-plus.fa-fw.fa-lg
    = mail_to "dstwen@gmail.com", nil, encode: "hex"
      i.fa.fa-envelope.fa-fw.fa-lg

app/views/layouts/_subscribe_button.html.slim
a.btn.btn-primary type="button" data-toggle="modal" data-target="#email-modal" style="margin-bottom: 20px;"
  - word = ["if entertained", "if I made ya think", "if you're nice", "- please?", "<3", "la!", " - you'll like it", "- everyone's doing it"]
  = "Subscribe #{word.sample}"

app/views/layouts/_subscribe_link.html.slim
.rss-holder type="button" data-toggle="modal" data-target="#email-modal"
  = "Subscribe  "
  i.fa.fa-rss

app/views/layouts/_subscribe_link_as_sentence.html.slim
a.email-subscribe-link-as-sentence type="button" data-toggle="modal" data-target="#email-modal"
  | Subscribe to his musings.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%;">
<head>
  <%= metamagic :title => "David Wen ⋅ Just Say Wen ⋅ 溫上霆", :description => "My name is David Wen. This is a place for me to plan, do, and reflect on my life. Professionally, I'm an entrepreneur, software developer, and management consultant. Personally, I like to backpack travel, take photos, write, and play sports where height matters. Here's a glimpse into me, and if you'd like to know me better, let's connect. Just say Wen."
  %>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <!-- jQuery -->
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <!-- jQuery UI -->
  <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"></script>
  <!-- Ensure propore rendering and touch zooming -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Google fonts -->
  <link href='https://fonts.googleapis.com/css?family=Sacramento' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:300, 400' rel='stylesheet' type='text/css'>
  <!-- Google Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-4320795-4', 'justsaywen.com');
    ga('send', 'pageview');

  </script>
    <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4320795-4']);
  _gaq.push(['_trackPageview']);
  (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

  ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';

  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>

  <script>
    (function (w, d, s, o, f, js, fjs) {
      w['Trust-Widget'] = o; w[o] = w[o] || function () {(w[o].q = w[o].q || []).push(arguments)};
      js = d.createElement(s), fjs = d.getElementsByTagName(s)[0];
      js.id = o; js.src = f; js.async = 1; fjs.parentNode.insertBefore(js, fjs);
    }(window, document, 'script', 'mw', 'https://trust-observer.s3.amazonaws.com/widget.js'));
    mw('init', { id: '6dd0a72d-20ed-4e04-8f4e-9fcdb7f1a9e5' });
  </script>
</head>
<body>
  <div class="container">
    <%= render "layouts/email_subscribe" %>
    <%= yield %>
  </div>
</body>
</html>